# .streamlit/secrets.toml
[firebase]
type = "service_account"
project_id = "ap-app-2007e"
private_key_id = "2cbb01b9fcdc116293e62656d6bd5897d6397440"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCZLwxtIvIbI8Sk
8B16H/jUr4fPqPeK7iq44UDEQOE504keFYd/LGrAH9GDYSeC2YYCyHoooMMac41x
0GbKKWIwvPtzCrj3AAKfPsqFM8AmX3WjWFpA2OOLEdXiF6rpY3JJONapktC3k+iW
o2R+AqlDdRLrK0ReigesCgrTmkMRs5/dsSXp5xWeg8I51L5xj/4rQrGL8W3NR/c5
YBv6c8eyjkrHgNVHKuIf71f8nZ1Jw1ISUKv4JpsvYtiW7z7XfJOxsBWJEnjXu8kZ
nb90UcMgZU0eU5dNBn8vVOkXUFJOtVddl97NFME8joQmvs+EPV7RH/Te8y/HSZO1s
mYc/63ZdAgMBAAECggEABIs4uyQGOnfdJWdZ+H1qTCTIyoggj6Zw7fsAiNHD3ItB
znfqlgkg3AmvvMw52tZLuPrbjqMDcCLTUxUOBSQ3hM8DnVIpE4k7FxSN/rmPSl1DN
nlILSaooEdeOZjJNXJoUkprdg5rbMKiXhCFbgbDx3+OBIJ2GpLYS6pYfGunAg/S1j
FpgShgi09/JIErz/bBUsU+ESfQMWVZatoWI8kM/WY4QVGLAek7DQ0GZPdqyUsZHh
ZoWPV6SpUbo9TVnEKd2urHcDRImwpWi8DFlCPiYNviOl22dNdWTMkmAWgZsLQ7jS
lGwKPEP3Zidw0zWMeGY9FbROVv017V1IjSbHcbwEAQKBgQDOMDIsmREbOsZ3iWkW
U41uyIa02mdWClEt9YHhkA/Fy22tkuxFFxZ0rQgmmnLFZq4u9Fg2fC6mumjCT7us
KsVvRjRrVjh56CIsK6dVU1ZZoskC+rOkGJHHU6xz3yGLadKJXGIoyr/j3x7oKQNz
Y0OsqlN3bO6ErLB9lelh6xnaoQKBgQC+MMRbilpSzCJsyyTJr9dQCYeG9Dqjya2r
wk4rQ+KITxkosUJ8uR1Q2Cd5ax3CAdJgKr/Z71N7hE+MUumg8gTQ6Sdrkx7YEzy2
nmM37t5UtpcOvIWr1py1dG833qOSyChX29b/bjrFA2TROekLoJe1hsozGMvP0tZx7
nG0DsX/OePQKBgDxn4ksujNRtY7ehiigAUm8iUFSrp5qNazsLsgFjMzu/XWJ8qLuV
nB/8msjydAwLSEjWvYCiWORSfiBFlSpYl8IWpC7JmkCUm3NwT7fIReDrKdhlpWTe5
n+vtqiBtqQ2mUlxmm9xr8Szt3IpbhbSFg83Kic9GJGFfGZ/6K/NSzC+ABAoGAGt02
njxuOwI02+5kCHD7rMdH2w7gxpDrzfgRXGENhdxF9I0NOeeGH44h0ovDfZizts0m2
niakFaLf6qH55o5Mr3Pph6A8C11B4Te5tgfWfa7AzYMReoE452SH5SNchXoiQK67w
np6mTHe7QNZmNY88fpaIbwk8mKFWSwczKsdinx50CgYBcNOgIOQCS9DuW9RtA29UJ
nm2sT8nT2cYNNIvaCoXRKxOKMxp1DnojZL6M/V3Whs0P13MaZR3XqJJ4Nh9ixN11v
nS8aIM6EKS9QK4y3//SZoZAOxByVq4oaVpUieAkVh2nBnag94ET5v/fake8azzq9T
nOw0BojXLZUJLm/mlVg2n+Q==
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@ap-app-2007e.iam.gserviceaccount.com"
client_id = "112754156604500677808"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40ap-app-2007e.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

